#include <gtest/gtest.h>

#include <LiteNN.h>
#include <LiteNN/Runtime/Interpreter.h>

#ifdef LITENN_ENABLE_MLIR
#include <LiteNN/Compiler/CompiledModule.h>
#endif

#include <array>
#include <span>
#include <vector>

using namespace LiteNN;

namespace
{
	float ReadFloat(const Tensor<CPU>& tensor, std::size_t index)
	{
		return static_cast<const float*>(tensor.RawData())[index];
	}

	Graph BuildReLULinearGraph()
	{
		Graph graph;
		Subgraph sg;
		const auto input = sg.AddParam(DataType::Float32, { 2, 3 });
		const auto weight = sg.AddNode(ConstantNode{
		                                   Tensor<CPU>({
		                                                   0.25, -1.0,
		                                                   2.0, 0.5,
		                                                   -0.75, 1.5,
		                                               },
		                                               { 3, 2 })
		                                       .CopyToDevice(PolymorphicDevice{ CPU{} }) },
		                               { OutputInfo{ DataType::Float32, { 3, 2 } } });
		const auto bias = sg.AddNode(ConstantNode{ Tensor<CPU>({ 0.1, -0.2 }, { 1, 2 })
		                                               .CopyToDevice(PolymorphicDevice{ CPU{} }) },
		                             { OutputInfo{ DataType::Float32, { 1, 2 } } });
		const auto matmul = sg.AddNode(BinaryOpNode{ BinaryOp::MatMul, { input, 0 }, { weight, 0 } },
		                               { OutputInfo{ DataType::Float32, { 2, 2 } } });
		const auto shifted = sg.AddNode(BinaryOpNode{ BinaryOp::Add, { matmul, 0 }, { bias, 0 } },
		                                { OutputInfo{ DataType::Float32, { 2, 2 } } });
		const auto zero = sg.AddNode(ConstantNode{ Tensor<CPU>({ 0.0 }, { 1 }).CopyToDevice(PolymorphicDevice{ CPU{} }) },
		                             { OutputInfo{ DataType::Float32, { 1 } } });
		const auto output = sg.AddNode(BinaryOpNode{ BinaryOp::Max, { shifted, 0 }, { zero, 0 } },
		                               { OutputInfo{ DataType::Float32, { 2, 2 } } });
		sg.SetResults({ { output, 0 } });
		graph.AddSubgraph(std::move(sg));
		graph.SetForward(0);
		graph.SetInputNames({ "x" });
		graph.SetOutputNames({ "relu_linear" });
		return graph;
	}

	void ExpectPyTorchGolden(const Tensor<CPU>& output)
	{
		// Generated by torch.relu(x @ w + b) for the fixture tensors above.
		const std::array<float, 4> expected{ 0.0F, 0.0F, 6.85F, 0.0F };
		ASSERT_EQ(output.Shape().ToOwned(), (std::vector<std::size_t>{ 2, 2 }));
		for (std::size_t i = 0; i < expected.size(); ++i)
		{
			EXPECT_NEAR(ReadFloat(output, i), expected[i], 1e-5F) << "index=" << i;
		}
	}

	std::array<Tensor<CPU>, 1> MakeInputs()
	{
		return {
			Tensor<CPU>({
			                1.0, -2.0, 0.5,
			                0.0, 3.0, -1.0,
			            },
			            { 2, 3 })
		};
	}
} // namespace

TEST(PyTorchGolden, ReLULinearInterpreterMatchesFixture)
{
	auto graph = BuildReLULinearGraph();
	auto inputs = MakeInputs();
	Runtime::Interpreter<CPU> interpreter;

	const auto outputs = interpreter.RunForward(graph, std::span<const Tensor<CPU>>(inputs));
	ASSERT_EQ(outputs.size(), 1u);
	ExpectPyTorchGolden(outputs[0]);
}

#ifdef LITENN_ENABLE_MLIR
TEST(PyTorchGolden, ReLULinearCPUArtifactMatchesFixture)
{
	auto graph = BuildReLULinearGraph();
	auto inputs = MakeInputs();

	auto artifact = Compiler<CPU>::CompileArtifact(graph);
	auto module = artifact.Load();
	const auto outputs = module.Run(std::span<const Tensor<CPU>>(inputs));

	ASSERT_EQ(outputs.size(), 1u);
	ExpectPyTorchGolden(outputs[0]);
}
#endif
