#include <gtest/gtest.h>

#include <LiteNN.h>
#include <LiteNN/Runtime/Interpreter.h>
#include <LiteNN/Serialization/TorchManifest.h>

#ifdef LITENN_ENABLE_MLIR
#include <LiteNN/Compiler/CompiledModule.h>
#endif

#include <algorithm>
#include <array>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <span>
#include <stdexcept>
#include <string>
#include <string_view>
#include <vector>

using namespace LiteNN;

namespace
{
	void AppendU64LE(std::vector<std::byte>& out, std::uint64_t value)
	{
		for (int i = 0; i < 8; ++i)
		{
			out.push_back(static_cast<std::byte>((value >> (8 * i)) & 0xffU));
		}
	}

	template <typename T>
	void AppendValue(std::vector<std::byte>& out, const T& value)
	{
		const auto oldSize = out.size();
		out.resize(oldSize + sizeof(T));
		std::memcpy(out.data() + oldSize, &value, sizeof(T));
	}

	std::vector<std::byte> BuildSafetensors(std::string header, std::vector<std::byte> payload)
	{
		std::vector<std::byte> bytes;
		AppendU64LE(bytes, header.size());
		for (const auto c : header)
		{
			bytes.push_back(static_cast<std::byte>(static_cast<unsigned char>(c)));
		}
		bytes.insert(bytes.end(), payload.begin(), payload.end());
		return bytes;
	}

	Serialization::SafetensorsArchive BuildLinearArchive(bool includeExtra = false)
	{
		std::vector<std::byte> payload;
		for (const auto value : std::array<float, 6>{ 0.25F, 2.0F, -0.75F, -1.0F, 0.5F, 1.5F })
		{
			AppendValue(payload, value);
		}
		for (const auto value : std::array<float, 2>{ 0.1F, -0.2F })
		{
			AppendValue(payload, value);
		}
		if (includeExtra)
		{
			AppendValue(payload, 42.0F);
		}

		const auto header = includeExtra
		                        ? R"({"linear.weight":{"dtype":"F32","shape":[2,3],"data_offsets":[0,24]},"linear.bias":{"dtype":"F32","shape":[2],"data_offsets":[24,32]},"unused.weight":{"dtype":"F32","shape":[1],"data_offsets":[32,36]}})"
		                        : R"({"linear.weight":{"dtype":"F32","shape":[2,3],"data_offsets":[0,24]},"linear.bias":{"dtype":"F32","shape":[2],"data_offsets":[24,32]}})";
		return Serialization::SafetensorsArchive::Load(BuildSafetensors(header, std::move(payload)));
	}

	std::string BuildLinearManifest(std::string_view weightDType = "F32",
	                                std::string_view weightShape = "[3,2]",
	                                std::string_view weightSource = "linear.weight",
	                                std::string_view weightLayout = "torch_linear_weight",
	                                std::string_view weightSourceShape = "[2,3]")
	{
		return std::string(R"({
  "format":"litenn.torch_manifest.v1",
  "inputs":[{"name":"x","dtype":"torch.float32","shape":[2,3]}],
  "tensors":[
    {"name":"fc.weight","source":")") + std::string(weightSource) + R"(","dtype":")" +
		       std::string(weightDType) + R"(","source_shape":)" + std::string(weightSourceShape) + R"(,"layout":")" +
		       std::string(weightLayout) + R"(","shape":)" + std::string(weightShape) + R"(},
    {"name":"fc.bias","source":"linear.bias","dtype":"F32","source_shape":[2],"layout":"torch_bias_1d","shape":[1,2]}
  ],
  "nodes":[
    {"name":"fc","op":"linear","input":"x","weight":"fc.weight","bias":"fc.bias","output":"fc_out"},
    {"name":"relu","op":"relu","input":"fc_out","output":"relu_linear"}
  ],
  "outputs":["relu_linear"]
})";
	}

	float ReadFloat(const Tensor<CPU>& tensor, std::size_t index)
	{
		return static_cast<const float*>(tensor.RawData())[index];
	}

	std::array<Tensor<CPU>, 1> MakeInputs()
	{
		return {
			Tensor<CPU>({
			                1.0, -2.0, 0.5,
			                0.0, 3.0, -1.0,
			            },
			            { 2, 3 })
		};
	}

	void ExpectPyTorchLinearReluGolden(const Tensor<CPU>& output)
	{
		// Generated by PyTorch: torch.relu(torch.nn.functional.linear(x, weight, bias)).
		const std::array<float, 4> expected{ 0.0F, 0.0F, 6.85F, 0.0F };
		ASSERT_EQ(output.Shape().ToOwned(), (std::vector<std::size_t>{ 2, 2 }));
		for (std::size_t i = 0; i < expected.size(); ++i)
		{
			EXPECT_NEAR(ReadFloat(output, i), expected[i], 1e-5F) << i;
		}
	}

	void ExpectManifestError(std::string manifest, const Serialization::SafetensorsArchive& archive,
	                         std::string_view expected)
	{
		try
		{
			(void)Serialization::ImportTorchManifest(manifest, archive);
			FAIL() << "expected manifest import to throw";
		}
		catch (const std::runtime_error& ex)
		{
			const std::string message = ex.what();
			EXPECT_NE(message.find(expected), std::string::npos) << message;
		}
	}
} // namespace

TEST(TorchManifest, ReportsSupportedMappingsAndDTypeAliases)
{
	const auto mappings = Serialization::SupportedTorchManifestOpMappings();
	const auto hasLinear = std::ranges::any_of(mappings, [](const auto& mapping) {
		return mapping.torchOp == "linear";
	});
	const auto hasLayerNorm = std::ranges::any_of(mappings, [](const auto& mapping) {
		return mapping.torchOp == "layer_norm";
	});
	EXPECT_TRUE(hasLinear);
	EXPECT_TRUE(hasLayerNorm);
	EXPECT_EQ(Serialization::MapTorchManifestDataType("torch.float32"), DataType::Float32);
	EXPECT_EQ(Serialization::MapTorchManifestDataType("torch.long"), DataType::Int64);
}

TEST(TorchManifest, ImportsTorchLinearReluManifestAndRunsGolden)
{
	const auto archive = BuildLinearArchive();
	auto result = Serialization::ImportTorchManifest(BuildLinearManifest(), archive);

	ASSERT_EQ(result.graph.VariableCount(), 2u);
	ASSERT_TRUE(result.graph.FindVariable("fc.weight").has_value());
	ASSERT_TRUE(result.graph.FindVariable("fc.bias").has_value());
	EXPECT_EQ(result.graph.GetVariable(*result.graph.FindVariable("fc.weight"))->Data().Shape().ToOwned(),
	          (std::vector<std::size_t>{ 3, 2 }));
	EXPECT_EQ(result.graph.GetVariable(*result.graph.FindVariable("fc.bias"))->Data().Shape().ToOwned(),
	          (std::vector<std::size_t>{ 1, 2 }));
	EXPECT_EQ(result.graph.InputSignature()[0].name, "x");
	EXPECT_EQ(result.graph.OutputSignature()[0].name, "relu_linear");
	EXPECT_EQ(result.report.importedTensors.size(), 2u);
	EXPECT_EQ(result.report.loweredOps.size(), 2u);
	EXPECT_FALSE(result.report.foldedConstants.empty());

	auto inputs = MakeInputs();
	Runtime::Interpreter<CPU> interpreter;
	const auto outputs = interpreter.RunForward(result.graph, std::span<const Tensor<CPU>>(inputs));
	ASSERT_EQ(outputs.size(), 1u);
	ExpectPyTorchLinearReluGolden(outputs[0]);

#ifdef LITENN_ENABLE_MLIR
	auto module = Compiler<CPU>::Compile(result.graph);
	const auto compiledOutputs = module.Run(std::span<const Tensor<CPU>>(inputs));
	ASSERT_EQ(compiledOutputs.size(), 1u);
	ExpectPyTorchLinearReluGolden(compiledOutputs[0]);
#endif
}

TEST(TorchManifest, ReportsManifestTensorDiagnostics)
{
	const auto archive = BuildLinearArchive();
	ExpectManifestError(BuildLinearManifest("BF16"), archive, "dtype mismatch");
	ExpectManifestError(BuildLinearManifest("F32", "[4,2]"), archive, "shape mismatch");
	ExpectManifestError(BuildLinearManifest("F32", "[3,2]", "missing.weight"), archive, "was not found");
	ExpectManifestError(BuildLinearManifest("F32", "[2]", "linear.bias", "torch_linear_weight", "[2]"), archive,
	                    "expects rank-2");

	const auto extraArchive = BuildLinearArchive(true);
	ExpectManifestError(BuildLinearManifest(), extraArchive, "extra tensor");
}
