name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
        - name: checkout
          uses: actions/checkout@v6
          with:
            submodules: true
        - name: configure-build-env
          run: |
            sudo add-apt-repository ppa:ubuntu-toolchain-r/test
            test -f /usr/share/doc/kitware-archive-keyring/copyright ||
            wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
            wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
            echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ noble main' | sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null
            echo 'deb http://apt.llvm.org/noble/ llvm-toolchain-noble main' | sudo tee /etc/apt/sources.list.d/llvm-toolchain.list >/dev/null
            sudo apt update
            sudo apt install g++-16 cmake libmlir-23-dev mlir-23-tools libzstd-dev libedit-dev ninja-build
        - name: build
          run: |
            /usr/bin/cmake -S . -B build -G Ninja -DCMAKE_C_COMPILER=/usr/bin/gcc-16 -DCMAKE_CXX_COMPILER=/usr/bin/g++-16 -DCMAKE_BUILD_TYPE=Release -DLITENN_ENABLE_MLIR=ON -DLITENN_BUILD_BENCHMARKS=ON -DCMAKE_PREFIX_PATH=/usr/lib/llvm-23/lib/cmake/mlir
            /usr/bin/cmake --build build --parallel
        - name: test
          run: |
            /usr/bin/ctest -j4 -C Debug --test-dir build -T test --output-on-failure
