name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
        - name: checkout
          uses: actions/checkout@v6
          with:
            submodules: true
        - name: configure-build-env
          run: |
            sudo add-apt-repository ppa:ubuntu-toolchain-r/test
            test -f /usr/share/doc/kitware-archive-keyring/copyright ||
            wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
            echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ noble main' | sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null
            sudo apt update
            sudo apt install g++-16 cmake
        - name: build
          run: |
            /usr/bin/cmake -S . -B build -G Ninja -DCMAKE_CXX_COMPILER=/usr/bin/g++-16
            /usr/bin/cmake --build build --parallel
        - name: test
          run: |
            /usr/bin/ctest -j4 -C Debug --test-dir build -T test --output-on-failure
